# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_design.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1796, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget = QtWidgets.QDockWidget(self.centralwidget)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 30, -1, 30)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.inputR = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputR.setObjectName("inputR")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputR)
        self.inputZeroI = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputZeroI.setObjectName("inputZeroI")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputZeroI)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.recalButn = QtWidgets.QPushButton(self.groupBox_2)
        self.recalButn.setObjectName("recalButn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.recalButn)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.inputYS = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputYS.setObjectName("inputYS")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputYS)
        self.plotBox = QtWidgets.QTabWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotBox.sizePolicy().hasHeightForWidth())
        self.plotBox.setSizePolicy(sizePolicy)
        self.plotBox.setMinimumSize(QtCore.QSize(0, 600))
        self.plotBox.setObjectName("plotBox")
        self.rawParams = QtWidgets.QWidget()
        self.rawParams.setObjectName("rawParams")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.rawParams)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.rawOverlayIntegrationChk = QtWidgets.QCheckBox(self.rawParams)
        self.rawOverlayIntegrationChk.setObjectName("rawOverlayIntegrationChk")
        self.verticalLayout_9.addWidget(self.rawOverlayIntegrationChk)
        self.rawOverlayVChk = QtWidgets.QCheckBox(self.rawParams)
        self.rawOverlayVChk.setObjectName("rawOverlayVChk")
        self.verticalLayout_9.addWidget(self.rawOverlayVChk)
        self.startSlider = QtWidgets.QWidget(self.rawParams)
        self.startSlider.setMaximumSize(QtCore.QSize(16777215, 55))
        self.startSlider.setObjectName("startSlider")
        self.gridLayout = QtWidgets.QGridLayout(self.startSlider)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rawStartLL = QtWidgets.QLabel(self.startSlider)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawStartLL.sizePolicy().hasHeightForWidth())
        self.rawStartLL.setSizePolicy(sizePolicy)
        self.rawStartLL.setObjectName("rawStartLL")
        self.horizontalLayout_4.addWidget(self.rawStartLL)
        self.startInp = QtWidgets.QSpinBox(self.startSlider)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startInp.sizePolicy().hasHeightForWidth())
        self.startInp.setSizePolicy(sizePolicy)
        self.startInp.setMinimumSize(QtCore.QSize(100, 0))
        self.startInp.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.startInp.setAlignment(QtCore.Qt.AlignCenter)
        self.startInp.setObjectName("startInp")
        self.horizontalLayout_4.addWidget(self.startInp)
        self.rawStartRL = QtWidgets.QLabel(self.startSlider)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawStartRL.sizePolicy().hasHeightForWidth())
        self.rawStartRL.setSizePolicy(sizePolicy)
        self.rawStartRL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rawStartRL.setObjectName("rawStartRL")
        self.horizontalLayout_4.addWidget(self.rawStartRL)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 5)
        self.horizontalLayout_4.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.rawStartSld = QtWidgets.QSlider(self.startSlider)
        self.rawStartSld.setMaximum(10000)
        self.rawStartSld.setOrientation(QtCore.Qt.Horizontal)
        self.rawStartSld.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.rawStartSld.setTickInterval(100)
        self.rawStartSld.setObjectName("rawStartSld")
        self.gridLayout.addWidget(self.rawStartSld, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.verticalLayout_9.addWidget(self.startSlider)
        self.rangeSlider = QtWidgets.QWidget(self.rawParams)
        self.rangeSlider.setMaximumSize(QtCore.QSize(16777215, 55))
        self.rangeSlider.setObjectName("rangeSlider")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.rangeSlider)
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setHorizontalSpacing(1)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rawRangeSld = QtWidgets.QSlider(self.rangeSlider)
        self.rawRangeSld.setMaximum(1000)
        self.rawRangeSld.setOrientation(QtCore.Qt.Horizontal)
        self.rawRangeSld.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.rawRangeSld.setTickInterval(10)
        self.rawRangeSld.setObjectName("rawRangeSld")
        self.gridLayout_4.addWidget(self.rawRangeSld, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rawRangeLL = QtWidgets.QLabel(self.rangeSlider)
        self.rawRangeLL.setObjectName("rawRangeLL")
        self.horizontalLayout_7.addWidget(self.rawRangeLL)
        self.rangeInp = QtWidgets.QSpinBox(self.rangeSlider)
        self.rangeInp.setMinimumSize(QtCore.QSize(100, 0))
        self.rangeInp.setAlignment(QtCore.Qt.AlignCenter)
        self.rangeInp.setObjectName("rangeInp")
        self.horizontalLayout_7.addWidget(self.rangeInp)
        self.rawRangeRL = QtWidgets.QLabel(self.rangeSlider)
        self.rawRangeRL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rawRangeRL.setObjectName("rawRangeRL")
        self.horizontalLayout_7.addWidget(self.rawRangeRL)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(2, 1)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.verticalLayout_9.addWidget(self.rangeSlider)
        self.drawButn = QtWidgets.QPushButton(self.rawParams)
        self.drawButn.setObjectName("drawButn")
        self.verticalLayout_9.addWidget(self.drawButn)
        self.toolButton = QtWidgets.QToolButton(self.rawParams)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_9.addWidget(self.toolButton)
        self.plotBox.addTab(self.rawParams, "")
        self.intergatedParams = QtWidgets.QWidget()
        self.intergatedParams.setObjectName("intergatedParams")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.intergatedParams)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.inp_pulse1_prior = QtWidgets.QLineEdit(self.intergatedParams)
        self.inp_pulse1_prior.setObjectName("inp_pulse1_prior")
        self.verticalLayout_7.addWidget(self.inp_pulse1_prior)
        self.inp_pulse1 = QtWidgets.QLineEdit(self.intergatedParams)
        self.inp_pulse1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.inp_pulse1.setObjectName("inp_pulse1")
        self.verticalLayout_7.addWidget(self.inp_pulse1)
        self.inp_pulse1_rest = QtWidgets.QLineEdit(self.intergatedParams)
        self.inp_pulse1_rest.setMaximumSize(QtCore.QSize(2222, 20))
        self.inp_pulse1_rest.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.inp_pulse1_rest.setObjectName("inp_pulse1_rest")
        self.verticalLayout_7.addWidget(self.inp_pulse1_rest)
        self.inp_pulse2 = QtWidgets.QLineEdit(self.intergatedParams)
        self.inp_pulse2.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.inp_pulse2.setObjectName("inp_pulse2")
        self.verticalLayout_7.addWidget(self.inp_pulse2)
        self.inp_pulse2_rest = QtWidgets.QLineEdit(self.intergatedParams)
        self.inp_pulse2_rest.setMaximumSize(QtCore.QSize(2222, 20))
        self.inp_pulse2_rest.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.inp_pulse2_rest.setObjectName("inp_pulse2_rest")
        self.verticalLayout_7.addWidget(self.inp_pulse2_rest)
        self.integrateButn = QtWidgets.QPushButton(self.intergatedParams)
        self.integrateButn.setObjectName("integrateButn")
        self.verticalLayout_7.addWidget(self.integrateButn)
        self.plotBox.addTab(self.intergatedParams, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.intervalTable = QtWidgets.QTableWidget(self.tab)
        self.intervalTable.setGeometry(QtCore.QRect(0, 30, 204, 192))
        self.intervalTable.setColumnCount(2)
        self.intervalTable.setObjectName("intervalTable")
        self.intervalTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.intervalTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.intervalTable.setHorizontalHeaderItem(1, item)
        self.addIntervalButton = QtWidgets.QPushButton(self.tab)
        self.addIntervalButton.setGeometry(QtCore.QRect(13, 230, 81, 23))
        self.addIntervalButton.setObjectName("addIntervalButton")
        self.intervalTable_2 = QtWidgets.QTableWidget(self.tab)
        self.intervalTable_2.setGeometry(QtCore.QRect(0, 290, 204, 231))
        self.intervalTable_2.setColumnCount(2)
        self.intervalTable_2.setObjectName("intervalTable_2")
        self.intervalTable_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.intervalTable_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.intervalTable_2.setHorizontalHeaderItem(1, item)
        self.addIntervalButton_2 = QtWidgets.QPushButton(self.tab)
        self.addIntervalButton_2.setGeometry(QtCore.QRect(10, 530, 91, 23))
        self.addIntervalButton_2.setObjectName("addIntervalButton_2")
        self.numberTrainingCyclesLine = QtWidgets.QLineEdit(self.tab)
        self.numberTrainingCyclesLine.setGeometry(QtCore.QRect(10, 0, 113, 20))
        self.numberTrainingCyclesLine.setObjectName("numberTrainingCyclesLine")
        self.numberEvalCyclesLine = QtWidgets.QLineEdit(self.tab)
        self.numberEvalCyclesLine.setGeometry(QtCore.QRect(10, 260, 113, 20))
        self.numberEvalCyclesLine.setObjectName("numberEvalCyclesLine")
        self.integrateButn_2 = QtWidgets.QPushButton(self.tab)
        self.integrateButn_2.setGeometry(QtCore.QRect(10, 550, 158, 23))
        self.integrateButn_2.setObjectName("integrateButn_2")
        self.removeIntervalButton = QtWidgets.QPushButton(self.tab)
        self.removeIntervalButton.setGeometry(QtCore.QRect(100, 230, 81, 23))
        self.removeIntervalButton.setObjectName("removeIntervalButton")
        self.removeIntervalButton_2 = QtWidgets.QPushButton(self.tab)
        self.removeIntervalButton_2.setGeometry(QtCore.QRect(110, 530, 81, 23))
        self.removeIntervalButton_2.setObjectName("removeIntervalButton_2")
        self.plotBox.addTab(self.tab, "")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.plotBox)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.holdPlotChk = QtWidgets.QCheckBox(self.groupBox)
        self.holdPlotChk.setObjectName("holdPlotChk")
        self.verticalLayout_4.addWidget(self.holdPlotChk)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.epochLengthLabel = QtWidgets.QLabel(self.centralwidget)
        self.epochLengthLabel.setText("")
        self.epochLengthLabel.setObjectName("epochLengthLabel")
        self.horizontalLayout_3.addWidget(self.epochLengthLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.trainCycLengthLabel = QtWidgets.QLabel(self.centralwidget)
        self.trainCycLengthLabel.setText("")
        self.trainCycLengthLabel.setObjectName("trainCycLengthLabel")
        self.horizontalLayout_5.addWidget(self.trainCycLengthLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.evalCycLengthLabel = QtWidgets.QLabel(self.centralwidget)
        self.evalCycLengthLabel.setText("")
        self.evalCycLengthLabel.setObjectName("evalCycLengthLabel")
        self.horizontalLayout_8.addWidget(self.evalCycLengthLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.filenameLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filenameLabel.sizePolicy().hasHeightForWidth())
        self.filenameLabel.setSizePolicy(sizePolicy)
        self.filenameLabel.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filenameLabel.setFont(font)
        self.filenameLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filenameLabel.setTextFormat(QtCore.Qt.RichText)
        self.filenameLabel.setWordWrap(True)
        self.filenameLabel.setObjectName("filenameLabel")
        self.verticalLayout_2.addWidget(self.filenameLabel)
        self.openButn = QtWidgets.QPushButton(self.centralwidget)
        self.openButn.setObjectName("openButn")
        self.verticalLayout_2.addWidget(self.openButn)
        self.reopenButn = QtWidgets.QPushButton(self.centralwidget)
        self.reopenButn.setObjectName("reopenButn")
        self.verticalLayout_2.addWidget(self.reopenButn)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1796, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.plotBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Ammeter settings"))
        self.label.setText(_translate("MainWindow", "R [Ohm]"))
        self.inputR.setText(_translate("MainWindow", "500"))
        self.inputZeroI.setText(_translate("MainWindow", "511"))
        self.label_2.setText(_translate("MainWindow", "Zero I point [10-bit ]"))
        self.recalButn.setText(_translate("MainWindow", "Recalculate"))
        self.label_3.setText(_translate("MainWindow", "Y scaling"))
        self.inputYS.setText(_translate("MainWindow", "1"))
        self.rawOverlayIntegrationChk.setText(_translate("MainWindow", "Overlay integrated current"))
        self.rawOverlayVChk.setText(_translate("MainWindow", "Overlay Voltage Pulses"))
        self.rawStartLL.setText(_translate("MainWindow", "Start"))
        self.rawStartRL.setText(_translate("MainWindow", "End"))
        self.rawRangeLL.setText(_translate("MainWindow", "Start"))
        self.rawRangeRL.setText(_translate("MainWindow", "End"))
        self.drawButn.setText(_translate("MainWindow", "Draw"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.plotBox.setTabText(self.plotBox.indexOf(self.rawParams), _translate("MainWindow", "Raw Data"))
        self.inp_pulse1_prior.setText(_translate("MainWindow", "0"))
        self.inp_pulse1.setText(_translate("MainWindow", "20"))
        self.inp_pulse1_rest.setText(_translate("MainWindow", "20"))
        self.inp_pulse2.setText(_translate("MainWindow", "20"))
        self.inp_pulse2_rest.setText(_translate("MainWindow", "20"))
        self.integrateButn.setText(_translate("MainWindow", "Draw"))
        self.plotBox.setTabText(self.plotBox.indexOf(self.intergatedParams), _translate("MainWindow", "Integrated"))
        item = self.intervalTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Length"))
        item = self.intervalTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Plot?"))
        self.addIntervalButton.setText(_translate("MainWindow", "Add"))
        item = self.intervalTable_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Length"))
        item = self.intervalTable_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Plot?"))
        self.addIntervalButton_2.setText(_translate("MainWindow", "Add"))
        self.numberTrainingCyclesLine.setText(_translate("MainWindow", "10"))
        self.numberEvalCyclesLine.setText(_translate("MainWindow", "3"))
        self.integrateButn_2.setText(_translate("MainWindow", "Draw"))
        self.removeIntervalButton.setText(_translate("MainWindow", "Remove"))
        self.removeIntervalButton_2.setText(_translate("MainWindow", "Remove"))
        self.plotBox.setTabText(self.plotBox.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.holdPlotChk.setText(_translate("MainWindow", "Keep previous plot"))
        self.label_4.setText(_translate("MainWindow", "Epoch Length:"))
        self.label_5.setText(_translate("MainWindow", "Training Cycle Length:"))
        self.label_7.setText(_translate("MainWindow", "Evaluation Cycle Length:"))
        self.filenameLabel.setText(_translate("MainWindow", "No files open"))
        self.openButn.setText(_translate("MainWindow", "Open"))
        self.reopenButn.setText(_translate("MainWindow", "Re-open the same file"))

